/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedBookResponse {
  borrowedDate?: string;
  borrower?: string;
  comment?: string;
  id?: number;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  returnedDate?: string;
  title?: string;
}
