spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bsn}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # auto-creates/updates tables
    show-sql: false # print SQL in console
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 8640000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account

server:
  port: 8080